=== razrog/pipl_test/linkedin_schema.json
{"$schema": "http://json-schema.org/draft-04/schema#","type": "object","properties":{"Jobs":{"type": "array","properties":{"company": {"type": "string"},"description": {"type": "string"},"start_date": {"type": "string"},"end_date": {"type": "string"},"title": {"type": "string"}}},"Name": {"type": "object","properties":{"middle": {"type": "string"},"last": {"type": "string"},"First": {"type": "string"}}},"summary":{"type": "string"},"Connections": {"type": "string"},"specialties": {"type": "string"},"image_url": {"type": "string"},"Location": {"type": "object","properties":{"country": {"type": "string"},"state": {"type": "string"},"city": {"type": "string"}}},"Recommendations": {"type": "string"},"profile_url": {"type": "string"}}}

=== razrog/pipl_test/out/55_a7f6a6b4c02d0f87.PROFILE.json
{"Jobs": [{"company": "Northants Triathlon Club", "title": "Triathlon Coach", "description": "', '    I am a level 2 coach, currently doing the level 3.  Due to finish November 2012.', '', 'Club coach for Northants Triathlon club. Coaching the adult club and also lead coach for the junior triathlon section.', '', 'Swim coach for Wootton Road Runners club.', '', 'I also have experience of coaching open water.', '", "end_date": "", "start_date": "January 2007"}, {"company": "L3Studios", "title": "owner", "description": "', '    Looking at the latest technologies and creative ideas to develop applications, interactive games and content for various hardware such as hand held devices (i.e. mobile / ipad)', '', 'Created a number of concepts for Augmented Reality applications (business as well as gaming) across various platforms.', '", "end_date": "November 2011", "start_date": "August 2010"}, {"company": "Walt Disney Internet Group", "title": "iTV Producer", "description": "", "end_date": "May 2007", "start_date": "June 2005"}, {"company": "Minds Eye Productions", "title": "General Manager", "description": "", "end_date": "June 2005", "start_date": "August 2004"}, {"company": "Minds Eye Productions", "title": "Producer", "description": "", "end_date": "July 2004", "start_date": "February 2003"}, {"company": "Peakviewing Transatlantic", "title": "Interactive TV Lead", "description": "", "end_date": "October 2002", "start_date": "February 2001"}, {"company": "Open Interactive", "title": "Interactive TV Service Developer", "description": "", "end_date": "January 2001", "start_date": "March 2000"}, {"company": "Dorling Kindersley Multimedia", "title": "Production Coordinator", "description": "", "end_date": "December 1999", "start_date": "October 1995"}], "Name": {"middle": "", "last": "Prior", "First": "Gavin"}, "summary": "', '    A Producer/Project Manager of applications and games, I have a proven track record creating engaging entertainment for children and adults working with a wide variety of Intellectual Properties.', 'Successfully grew a department creating games for Sky Games, which in turn was eventually sold as a studio to Disney, where I oversaw multiple launches of both UK and international games products.', 'My expertise ranges across multiple technologies and well over 30 high-profile brands.', '", "Connections": "157", "specialties": "\\,r,\\,n,C,o,a,c,h,i,n,g,\\,r,\\,n,\\,r,\\,n,t,r,i,a,t,h,l,o,n,\\,r,\\,n,\\,r,\\,n,o,p,e,n,w,a,t,e,r,s,w,i,m,c,o,a,c,h,i,n,g,\\,r,\\,n,\\,r,\\,n,T,e,a,m,B,u,i,l,d,i,n,g,\\,r,\\,n,\\,r,\\,n,T,e,a,m,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,P,r,o,j,e,c,t,C,o,o,r,d,i,n,a,t,i,o,n,\\,r,\\,n,\\,r,\\,n,N,e,w,B,u,s,i,n,e,s,s,D,e,v,e,l,o,p,m,e,n,t,\\,r,\\,n,\\,r,\\,n,N,e,w,M,e,d,i,a,\\,r,\\,n,\\,r,\\,n,D,i,g,i,t,a,l,M,e,d,i,a,\\,r,\\,n,\\,r,\\,n,D,i,g,i,t,a,l,S,t,r,a,t,e,g,y,\\,r,\\,n,\\,r,\\,n,A,u,g,m,e,n,t,e,d,R,e,a,l,i,t,y,\\,r,\\,n,\\,r,\\,n,I,n,t,e,r,a,c,t,i,v,e,M,e,d,i,a,\\,r,\\,n,\\,r,\\,n,I,n,t,e,r,a,c,t,i,v,e,T,V,\\,r,\\,n,\\,r,\\,n,H,T,M,L,5,\\,r,\\,n,\\,r,\\,n,c,s,s,3,\\,r,\\,n,\\,r,\\,n,C,o,n,t,e,n,t,D,e,v,e,l,o,p,m,e,n,t,\\,r,\\,n,\\,r,\\,n,M,S,P,r,o,j,e,c,t,\\,r,\\,n,\\,r,\\,n,A,g,i,l,e,P,r,o,j,e,c,t,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,B,a,s,e,c,a,m,p,\\,r,\\,n", "image_url": "", "Location": {"country": "GB", "state": "England", "city": "Northampton"}, "Recommendations": "4", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVzX1ZIDuklPX7tZT4yg8er-lBktXPxei-KNCiNfzexQw&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_fef4ace96124d985.PROFILE.json
{"Jobs": [{"company": "Command Strategies", "title": "Senior Consultant", "description": "', 'Consulting in Business Development with a focus on the Federal Marketplace.', '", "end_date": "", "start_date": "January 2011"}], "Name": {"middle": "", "last": "Hutton", "First": "Dave"}, "summary": "", "Connections": "321", "specialties": "\\,r,\\,n,N,e,w,B,u,s,i,n,e,s,s,D,e,v,e,l,o,p,m,e,n,t,\\,r,\\,n,\\,r,\\,n,O,p,e,r,a,t,i,o,n,s,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,g,e,n,e,r,a,l,m,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,D,o,D,\\,r,\\,n,\\,r,\\,n,N,a,v,y,\\,r,\\,n,\\,r,\\,n,D,e,f,e,n,s,e,\\,r,\\,n,\\,r,\\,n,M,i,l,i,t,a,r,y,\\,r,\\,n,\\,r,\\,n,O,r,g,a,n,i,z,a,t,i,o,n,a,l,L,e,a,d,e,r,s,h,i,p,\\,r,\\,n,\\,r,\\,n,G,o,v,e,r,n,m,e,n,t,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-aA4wIIACGy7nGsOfSa6CCDI-wYJWzHOE7AehC7sCwwJcQoeraA4hmA4CwzgwQehjjVVe/dave-hutton.jpg", "Location": {"country": "US", "state": "MN", "city": "Minneapolis"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVI1bUiPjXH62l4gT-CkzZRQOF_KoSg9neWJc_XY25yxM&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_57f2afc5048514b0.PROFILE.json
{"Jobs": [{"company": "Hobbs Ltd", "title": "Business Analyst", "description": "", "end_date": "", "start_date": "September 2012"}, {"company": "Projmbiza Ltd", "title": "Owner and Director", "description": "', 'Projmbiza ltd offers both project management and business analysis services. Experience in Online Gaming, Retail eCommerce, Aviation, Media sectors.', '", "end_date": "", "start_date": "May 2010"}, {"company": "Tesco.com", "title": "Business Analyst", "description": "', 'Working on creating new strategic API (initial focus on mobile, grocery, non-grocery and clubcard):', \"analysing existing API's and Operations\", 'fitting these into new Enterprise model', \"writing IDL's (interface description language) documents for developers\", 'creating new processes where necessary', '", "end_date": "August 2012", "start_date": "May 2012"}, {"company": "Tigerspike", "title": "Digital Project Manager/Business Analyst", "description": "', 'Tigerspike are a technology company with a range of professional services who specialise in Personal Media (ipad, iphone, android).', '', 'technologies on project:', '.net, JSON, xcode, XML', '", "end_date": "May 2012", "start_date": "January 2012"}, {"company": "Easyjet", "title": "Business Analyst", "description": "', 'Working on Mobile and Desktop product relating to passenger checkin, bag drop etc.', '", "end_date": "January 2012", "start_date": "June 2011"}, {"company": "Motability Operations", "title": "Business Analyst", "description": "', \"Business Analyst focussing on changes to MO's core Dealership platform.\", '", "end_date": "June 2011", "start_date": "January 2011"}, {"company": "Salmon", "title": "Business Analyst", "description": "', \"I worked on Salmon's Argos account, creating functional specifications.\", '", "end_date": "November 2010", "start_date": "September 2010"}, {"company": "Blacks Leisure Group", "title": "Business Analyst", "description": "', 'Analysed Business Intelligence (Boxi) reporting requirements across multiple departments (Finance, Buying and Merchandising and Online/Internet etC), specifically identifying data elements that are missing from existing reports. I also created documentation on existing reporting processes to identify areas of improvement.', '", "end_date": "September 2010", "start_date": "April 2010"}, {"company": "LVS", "title": "Business Analyst/Documentation Manager", "description": "', \"Business Analyst on 2 major projects: 'Live Betting' and 'Affiliate Systems'.\", 'Author of EGP (Enterprise Gaming Platform) product user guide, CMS user guide and all release notes using JIRA. ', 'Documentation Manager - responsible for end user and technical documentation.', '", "end_date": "April 2010", "start_date": "February 2009"}, {"company": "Cloudcity", "title": "Head of Project Services", "description": "', 'ASP.net, c#, sql server development environment.', 'My primary focus was to improve Project communication between project team members and to introduce the Project Management discipline to the organisation, both of which were achieved. Cloudcity produce white labelled online trivia games which can be branded according to individual business alliance requirements and these games are used as a viral marketing tool. Cloudcity also have their own core product set which to date includes Football Trivia, Movie Trivia and Sci-Fi Trivia. ', '', 'The primary Project Management methodology used at Cloudcity was based on Agile development using SCRUM. I also introduced elements of the Waterfall approach to Project Management where applicable for example issue and risk logs.', '", "end_date": "August 2008", "start_date": "November 2007"}, {"company": "Ladbrokes eGaming", "title": "eCommerce Project Manager", "description": "', 'Project Manager on large ecommerce systems within a matrix management organisation.', 'Responsible for implementation of Online Payment Solutions (Alternative Payment Methods such as Neteller, Earthport, eNets, Entropay, 1-Pay as well as the Datacash payment gateway from Ladbrokes) for 2.5 years. ', 'Responsible for leading and managing the implementation of an IT Governance Product - Mercury ITG - (Demand Management, Project Management, Programme Management, Resource Management) for 2.5 years. Responsible for process analysis, process design, process development, dashboard development, product training, product support. Developed processes for Systems Change Requests, Small/Medium/Large Project requests, Bug, Issue and Scope Change requests.', '", "end_date": "November 2007", "start_date": "July 2002"}, {"company": "Kana", "title": "Technical Support Consultant", "description": "', \"Responsible for resolving customer issues with Kana's online marketing product. Required Oracle, Solaris technical skills to resolve issues as well as good product knowledge and industry sector knowledge.\", '", "end_date": "2002", "start_date": "2000"}, {"company": "CSF", "title": "Oracle Pre-Sales Consultant", "description": "', 'Onsite consultancy role, assisting Sales team with technical demonstration of Oracle plug-in to BMC Patrol.', '", "end_date": "2000", "start_date": "1999"}, {"company": "Lillywhites", "title": "Oracle DBA/Unix Systems Administrator", "description": "', 'Specialist Sports retail in Piccadily, London.', 'Lillywhites was sold to Sports Direct.com in 2002.', '", "end_date": "1999", "start_date": "1998"}], "Name": {"middle": "", "last": "Lester", "First": "Gary"}, "summary": "', '- Experience Business Analyst (10 years)', '- Experience Project Manager (7 years)', '- PRINCE2 Practitioner ', '- ISEB Certificate in Project Management', '- 3 years SCRUM experience', '- In the Online Gaming Industry for 6 years and have since been in the Retail, Insurance, Airline and most recently iPad/iPhone development industries', '', 'Current project:', '- Definition of the programming methods (Operations) needed for a new strategic Tesco API ', '- Definition of the user stories and acceptance criteria', '', 'In Past:', 'Tigerspike - Project Manager for Haaretz Newspaper (Israeli) iPad Application', \"Tigerspike - Project Manager for Random House's client iPhone Application (Yotam Ottolenghi - chef)\", '', '- Easyjet - new checkin system', '- Enhancements to Online Vehicle Purchase web based system at Motability Operations', '- Data Warehouse Project - BI reporting requirements (Boxi) ', \"- Live Betting and Affiliate System for France's National Lottery provider.\", '- Administrator and Developer of Mercury ITG (Project and Portfolio Management System) system for Ladbrokes eGaming.', '- Online Payments, CRM, Sports Retail and Pre-Sales Consultancy.', '", "Connections": "500+", "specialties": "\\,r,\\,n,P,r,o,j,e,c,t,P,o,r,t,f,o,l,i,o,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,S,h,a,r,e,P,o,i,n,t,\\,r,\\,n,\\,r,\\,n,O,n,l,i,n,e,A,d,v,e,r,t,i,s,i,n,g,\\,r,\\,n,\\,r,\\,n,S,E,O,\\,r,\\,n,\\,r,\\,n,D,a,t,a,b,a,s,e,s,\\,r,\\,n,\\,r,\\,n,A,i,r,l,i,n,e,s,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,P,R,I,N,C,E,2,\\,r,\\,n,\\,r,\\,n,A,g,i,l,e,M,e,t,h,o,d,o,l,o,g,i,e,s,\\,r,\\,n,\\,r,\\,n,E,-,c,o,m,m,e,r,c,e,\\,r,\\,n,\\,r,\\,n,A,g,i,l,e,P,r,o,j,e,c,t,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,S,c,r,u,m,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-vpH7qZpBGzmofyHdPvfhwR0xwJrrps3WkCHCw09Ew6xK0G_WvpHCYplBwywfpeWPwIgz/gary-lester.jpg", "Location": {"country": "GB", "state": "England", "city": "London"}, "Recommendations": "22", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVFXOXkK96abRl3clqxHt8153DMKfKwyUFdSNX48K2fj7&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_2468537c498d9ffd.PROFILE.json
{"Jobs": [{"company": "Imola Informatica", "title": "Senior Manager", "description": "", "end_date": "", "start_date": "January 2010"}, {"company": "Gruppo Imola", "title": "Technical  Sales Manager", "description": "", "end_date": "June 2011", "start_date": "October 2004"}, {"company": "Borland Software Corporation", "title": "Professional Solutions Manager", "description": "", "end_date": "September 2004", "start_date": "June 2000"}], "Name": {"middle": "Mauro", "last": "Vignati", "First": "Pier Mauro"}, "summary": "", "Connections": "197", "specialties": "", "image_url": "", "Location": {"country": "IT", "state": "Lombardia", "city": "Area Industriale"}, "Recommendations": "1", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVzDDXys_YcEbGsmB256bYjgXRxxoC93am7P1ZMMHF4TV&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_04efbb6cba79a9f5.PROFILE.json
{"Jobs": [{"company": "TAL Direct", "title": "Senior Software Developer", "description": "', 'TAL Direct is the leading direct insurance provider in Australia. It operates the InsuranceLine brand and numerous \"white label\" alliances producing life insurance products and services for businesses such as Virgin Money, NIB and IAG.', '', 'As a senior developer, my role includes software design, implementation and support for insurance products on the in-house sales and admin system, and the customer-facing website. Software is developed in an Agile environment using TDD.', '', 'The technologies utilised include C#, VB.NET, ASP.NET, SQL Server 2008, T-SQL, MSMQ, WCF, RESTful web services, Linq2SQL, DevExpress, NUnit, Rhinomocks, Specflow, Project White, CruiseControl and TeamCity.', '", "end_date": "", "start_date": "July 2011"}, {"company": "Department of Employment, Economic Development and Innovation", "title": ".NET Consultant", "description": "', 'Short-term contract to implement a system for classifying and tracking scientific samples, with a tight deadline and a rapidly assembled team of 3 consultants. We utilised the Scrum Agile methodology to implement the most important system components first, empowering us to deliver a working product within 4 weeks.', '', 'My role involved business analysis, story breakdown, system architecture and software development. We built the system using C#, ASP.NET, SQL Server 2008, WCF, Linq2SQL and NUnit for TDD.', '", "end_date": "July 2011", "start_date": "June 2011"}, {"company": "BNP Paribas", "title": "Strategic Developer", "description": "', 'BNP Paribas is one of the largest banks in the world, measured by total assets. As a strategic developer my role involved system architecture, business analysis, development and support for a range of Product Control and Financial Control / Middle Office applications.', '', 'The overall system consisted of a number of SQL Server 2000 & 2008 databases, C# WPF GUI, MQ feed, and legacy MSAccess databases.', '", "end_date": "September 2010", "start_date": "September 2009"}, {"company": "Pioneer Alternative Investments", "title": "Senior Systems Developer", "description": "', 'PAI is a fund of hedge funds and one of the leading companies in the alternative investments arena. Momentus is PAI\u2019s front office system, providing functionality for research and quantitative analysis, portfolio construction, investment management and reporting.', '', 'As a senior developer on the Momentus team and as one of a team of four, I was responsible for business analysis, system architecture, development and support. The system consisted of C# MVP Winforms and C# ASP.NET front ends, C# .NET remoting mid-tier, SQL Server 2000 database, Sharepoint 2003 and Reporting Services 2000.', '", "end_date": "September 2009", "start_date": "May 2008"}, {"company": "ABN Amro", "title": "Analyst Developer", "description": "', 'Osiris is a pricing, booking and risk management system for exotic interest rate derivatives. The system incorporates extensive use of distributed components and parallel processing, using a DataSynapse GridServer for complex pricing and risk sensitivity calculations and simulations.', '', 'As a senior developer on the Osiris team, I was responsible for reengineering the overnight pricing and risk system, migrating overnight risk reports to the GridServer framework and implementing a large number of features, bug fixes and utilities.', '", "end_date": "April 2008", "start_date": "April 2006"}, {"company": "BBC Technology", "title": "IT Systems Development Engineer", "description": "', 'Project Jupiter was the first project in the world to fully digitalise the newsroom environment. The system utilises a digital core of media servers to produce a tape-less production environment. This empowers editors and journalists to access, distribute and archive media from their desktop ingestion from satellite feed or tape.', '', 'As a core developer on the team I was involved at all stages of the project lifecycle, from requirement specification and design through to implementation, testing, bug fixing and performance improvements.', '", "end_date": "March 2006", "start_date": "April 2003"}, {"company": "B+W Electronic Systems (now Ryco)", "title": "Lead Applications Developer", "description": "', 'As a senior developer working in this rapidly growing telecommunications company (winner of the Deloitte and Touche Fast50 Award as one of the fastest growing companies in the UK and in the top 100 in Europe) I successfully developed critical applications that are currently in use throughout the world.', '", "end_date": "March 2003", "start_date": "May 1999"}], "Name": {"middle": "", "last": "Burns", "First": "Brendan"}, "summary": "', 'A pragmatic, creative and team-oriented software engineer with an excellent attitude and communication skills, backed up by extensive development experience and solid academic qualifications.', '", "Connections": "431", "specialties": "\\,r,\\,n,C,o,n,t,i,n,u,o,u,s,I,n,t,e,g,r,a,t,i,o,n,\\,r,\\,n,\\,r,\\,n,A,g,i,l,e,M,e,t,h,o,d,o,l,o,g,i,e,s,\\,r,\\,n,\\,r,\\,n,C,#,\\,r,\\,n,\\,r,\\,n,J,S,P,\\,r,\\,n,\\,r,\\,n,S,o,f,t,w,a,r,e,D,e,v,e,l,o,p,m,e,n,t,\\,r,\\,n,\\,r,\\,n,M,i,c,r,o,s,o,f,t,S,Q,L,S,e,r,v,e,r,\\,r,\\,n,\\,r,\\,n,T,D,D,\\,r,\\,n,\\,r,\\,n,.,N,E,T,\\,r,\\,n,\\,r,\\,n,S,Q,L,\\,r,\\,n,\\,r,\\,n,W,C,F,\\,r,\\,n,\\,r,\\,n,S,c,r,u,m,\\,r,\\,n,\\,r,\\,n,A,S,P,.,N,E,T,\\,r,\\,n,\\,r,\\,n,W,P,F,\\,r,\\,n,\\,r,\\,n,W,i,n,F,o,r,m,s,\\,r,\\,n,\\,r,\\,n,D,e,s,i,g,n,P,a,t,t,e,r,n,s,\\,r,\\,n,\\,r,\\,n,A,g,i,l,e,P,r,o,j,e,c,t,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,R,e,q,u,i,r,e,m,e,n,t,s,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,V,B,.,N,E,T,\\,r,\\,n,\\,r,\\,n,L,I,N,Q,\\,r,\\,n,\\,r,\\,n,A,p,p,l,i,c,a,t,i,o,n,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,S,o,l,u,t,i,o,n,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,S,u,b,v,e,r,s,i,o,n,\\,r,\\,n,\\,r,\\,n,O,r,a,c,l,e,\\,r,\\,n,\\,r,\\,n,T,-,S,Q,L,\\,r,\\,n,\\,r,\\,n,J,a,v,a,\\,r,\\,n,\\,r,\\,n,W,e,b,S,e,r,v,i,c,e,s,\\,r,\\,n,\\,r,\\,n,V,i,s,u,a,l,S,t,u,d,i,o,\\,r,\\,n,\\,r,\\,n,M,u,l,t,i,t,h,r,e,a,d,i,n,g,\\,r,\\,n,\\,r,\\,n,O,b,j,e,c,t,O,r,i,e,n,t,e,d,D,e,s,i,g,n,\\,r,\\,n,\\,r,\\,n,D,a,t,a,b,a,s,e,D,e,s,i,g,n,\\,r,\\,n,\\,r,\\,n,C,r,u,i,s,e,C,o,n,t,r,o,l,\\,r,\\,n,\\,r,\\,n,S,y,s,t,e,m,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,C,+,+,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-0WglTCMcAxljLDuquqGUlnKTF-UrHeGtpWgbc2jcFD0PHV680WgbzZdcFan6H5rrHqMD/brendan-burns.jpg", "Location": {"country": "AU", "state": "VIC", "city": "Port Melbourne"}, "Recommendations": "4", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVC1GHBtsbr-SVajLD-pJHkm7wg4Zmae_CGfZoa_2-8EY&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_0f9d4e3c21cf3432.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Maharaj", "First": "Moonesh"}, "summary": "", "Connections": "4", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "FL", "city": "Tampa"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVIxQ-Dvn1iwKLW6k1uBKeFomYM2ixA1VeLP-l-VJAN-s&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_2c1023f8d1f7d039.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Turdikulov", "First": "Azamat"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "DE", "state": "NDS", "city": "BS"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVKOrskhscsc-_KRnip9Ah9i1yiZjVhkjTZBed8ze3xe9&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_74155a36576b4bc5.PROFILE.json
{"Jobs": [{"company": "ING", "title": "building block architect for trade finance and bank guarantees", "description": "', '    working on IT strategy and roadmap', '", "end_date": "", "start_date": "July 2012"}], "Name": {"middle": "", "last": "Coenen", "First": "Jan"}, "summary": "', '    Working for the department of Enterprise Architecture at ING.', '', 'Focus on trade finance and bank guarantees.', 'Before this working as information architect and consultant for ING Banking. Specialized in IT solutions for \"savings\" & \"loans\". Interested in topics as, information strategy including e.g. application assessments, outsourcing etc.', 'Not only in this business for the money, but after office hours working as an artist (painting, drawing) on a professional level (see WWW.JanCoenen.NL).', '", "Connections": "174", "specialties": "\\,r,\\,n,B,u,s,i,n,e,s,s,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,I,n,f,o,r,m,a,t,i,o,n,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,T,e,c,h,n,o,l,o,g,y,P,l,a,n,n,i,n,g,\\,r,\\,n,\\,r,\\,n,I,n,f,o,r,m,a,t,i,o,n,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,F,i,n,e,A,r,t,\\,r,\\,n,\\,r,\\,n,I,n,f,o,r,m,a,t,i,o,n,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,I,C,T,\\,r,\\,n,\\,r,\\,n,P,r,o,c,e,s,s,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,P,R,I,N,C,E,2,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,E,n,t,e,r,p,r,i,s,e,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,F,u,n,c,t,i,o,n,a,l,D,e,s,i,g,n,\\,r,\\,n,\\,r,\\,n,T,O,G,A,F,\\,r,\\,n,\\,r,\\,n,P,h,o,t,o,s,h,o,p,\\,r,\\,n", "image_url": "", "Location": {"country": "NL", "state": "FL", "city": "Almere"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVBJaA4hPQY5ATH2WeRSrwSEAGznQ42FlR_q05mU-Pw5c&trk=pprof-0-ts-view_full-0"}
