=== razrog/pipl_test/linkedin_schema.json
{"$schema": "http://json-schema.org/draft-04/schema#","type": "object","properties":{"Jobs":{"type": "array","properties":{"company": {"type": "string"},"description": {"type": "string"},"start_date": {"type": "string"},"end_date": {"type": "string"},"title": {"type": "string"}}},"Name": {"type": "object","properties":{"middle": {"type": "string"},"last": {"type": "string"},"First": {"type": "string"}}},"summary":{"type": "string"},"Connections": {"type": "string"},"specialties": {"type": "string"},"image_url": {"type": "string"},"Location": {"type": "object","properties":{"country": {"type": "string"},"state": {"type": "string"},"city": {"type": "string"}}},"Recommendations": {"type": "string"},"profile_url": {"type": "string"}}}

=== razrog/pipl_test/out/55_11cc1be9286388ff.PROFILE.json
{"Jobs": [{"company": "Oracle Corporation", "title": "Senior Recruiter - EMEA Recruitment Team", "description": "', '    Currently focused on the UK&I and Western European organisations, recruiting into the Consulting and Development lines of business, hiring high potential Consultants and Architects with SOA, E2.0, Cloud and IDM skills and Developers and Testers with J2EE and Solaris specialist skills.', '', 'I also drive the recruitment for our very successful MySQL, Virtualisation and Linux Sales Consulting Global Business Unit, hiring talented Enterprise Sales Execs and Managers.', '", "end_date": "", "start_date": "March 2011"}, {"company": "IT Executive Ltd", "title": "Senior Associate", "description": "', '    A founder member of IT Executive Ltd which has been operating throughout the UK and Europe since 1998 as a specialist IT & Telecoms recruitment consultancy. ', '', 'Clients varied from start-ups to large corporates but regardless of size, I created bespoke solutions to meet their individual needs. Expertise covered contingency recruitment through database search and advertised selection, along with contingency search or one off retained assignment services for higher profile hiring needs.', '", "end_date": "March 2011", "start_date": "May 2010"}, {"company": "Hays Telecoms Ltd", "title": "Senior Consultant", "description": "', '    Contract & permanent recruitment within Telecoms Operations and Mobile/Wireless verticals.', '', 'Successfully turned around a failing contract PSL Account (Alcatel-Lucent), significantly improving both delivery within business critical programmes and the Hays profile amongst hiring managers and contractors.', '", "end_date": "March 2010", "start_date": "January 2009"}, {"company": "IT Executive Ltd", "title": "Business Development Manager", "description": "', '    Approached to join the owner in the start-up phase of the business. A 360 role as well as involvement in hiring and mentoring other Consultants.', '', 'Developed long term relationships with blue-chip and SME clients throughout the UK IT sector.', '", "end_date": "January 2009", "start_date": "December 1998"}, {"company": "Hays IT Ltd", "title": "Principal Consultant", "description": "', '    Promoted from Trainee to Principal Consultant within 12 months. Billed the highest permanent fees across the UK and European IT Divisions during 1997-1998 financial year.', '", "end_date": "1998", "start_date": "1996"}], "Name": {"middle": "", "last": "Carter", "First": "Simon"}, "summary": "', '    With 15 years external IT&T recruitment experience, I now work for Oracle as a Senior Recruiter across the Consulting, Sales Consulting, Development and Support lines of business, throughout Europe, Middle East & Africa. ', '', 'Why Oracle?....we provide the world\u2019s most complete, open, and integrated business software and hardware systems, with more than 370,000 customers\u2014including 100 of the Fortune 100\u2014representing a variety of sizes and industries in more than 145 countries around the globe. Now, with Sun server, storage, operating-system, and virtualization technology, Oracle is the only vendor able to offer a complete technology stack in which every layer is integrated to work together as a single system.', '', \"Starting more than 30 years ago with Oracle's innovative relational database, the Oracle stack today includes Oracle Enterprise Linux, Oracle VM, Oracle Fusion Middleware, and the largest and most complete set of industry and business applications software on the market. The addition of Sun storage and systems technology makes the Oracle stack complete.\", '', 'Oracle employees enjoy competitive salaries, an excellent flexible benefits scheme and a network of like-minded co-workers that drive innovation across the entire technology industry. Working at Oracle means working on innovative, leading technological developments. Do you want to become part of this? Then go to: http://emeajobs.oracle.com', '', 'All direct candidate queries regarding career opportunities at Oracle are welcome. Do not hesitate to contact me directly for an informal discussion - simon.carter@oracle.com', '", "Connections": "500+", "specialties": "\\,r,\\,n,R,e,c,r,u,i,t,i,n,g,\\,r,\\,n,\\,r,\\,n,A,c,c,o,u,n,t,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,D,e,v,e,l,o,p,m,e,n,t,\\,r,\\,n,\\,r,\\,n,T,e,c,h,n,i,c,a,l,R,e,c,r,u,i,t,i,n,g,\\,r,\\,n,\\,r,\\,n,E,x,e,c,u,t,i,v,e,S,e,a,r,c,h,\\,r,\\,n,\\,r,\\,n,B,e,n,e,f,i,t,s,N,e,g,o,t,i,a,t,i,o,n,\\,r,\\,n,\\,r,\\,n,T,a,l,e,n,t,A,c,q,u,i,s,i,t,i,o,n,\\,r,\\,n,\\,r,\\,n,S,o,u,r,c,i,n,g,\\,r,\\,n,\\,r,\\,n,C,o,n,t,r,a,c,t,R,e,c,r,u,i,t,m,e,n,t,\\,r,\\,n,\\,r,\\,n,I,n,t,e,r,n,e,t,R,e,c,r,u,i,t,i,n,g,\\,r,\\,n,\\,r,\\,n,S,c,r,e,e,n,i,n,g,R,e,s,u,m,e,s,\\,r,\\,n,\\,r,\\,n,T,a,l,e,n,t,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-uq6WM7Dm2P9oSCrP3AMrdnABpiJVvC4WAlMCYwAf0KJsnh4fal90K7APQ1JV_U-XkN/simon-carter.jpg", "Location": {"country": "GB", "state": "England", "city": "London"}, "Recommendations": "1", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVI62m9RF67DxRQo85-stcZgjv00GIN023_7Tu3MlL6kx&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_e97ef40443ab2723.PROFILE.json
{"Jobs": [{"company": "Pyramid-4", "title": "Independent Contract / Consult", "description": "", "end_date": "", "start_date": "March 1997"}, {"company": "Client:  Anchor Glass Container Corp.", "title": "EDI Specialist", "description": "", "end_date": "March 2012", "start_date": "October 2011"}, {"company": "Client: S&D Coffee, Concord, NC", "title": "EDI Programmer Analyst (Gentran for i-Series v4.0 / JD Edwards v7.3)", "description": "", "end_date": "March 2012", "start_date": "August 2007"}, {"company": "Liberty Hardware", "title": "EDI Specialist", "description": "", "end_date": "August 2011", "start_date": "May 2010"}, {"company": "Client: W.L. Gore", "title": "EDI Team Lead; Programmer Analyst (Inovis (Harbinger v2.11) / JD Edwards v7.3)", "description": "", "end_date": "August 2008", "start_date": "September 2006"}, {"company": "Client: Corning Cable Systems, Hickory, NC", "title": "EDI Analyst / Mapper (Gentran / SAP)", "description": "", "end_date": "September 2006", "start_date": "March 2006"}, {"company": "Client: Husqvarna Forest & Garden, Charlotte, NC", "title": "EDI Team Lead; Programmer Analyst (Extol / REX)", "description": "", "end_date": "December 2005", "start_date": "July 2004"}, {"company": "Client: S&D Coffee, Concord, NC", "title": "JD Edwards Programmer Analyst; Gentran EDI consult", "description": "", "end_date": "February 2004", "start_date": "March 2003"}, {"company": "Client: W.L. Gore, Newark, DE", "title": "EDI Programmer Analyst (Inovis (Harbinger v2.11) / JD Edwards v7.3)", "description": "", "end_date": "January 2003", "start_date": "April 2001"}, {"company": "Client: Regent Lighting / Cooper Lighting", "title": "EDI Project Lead; Programmer Analyst (Harbinger / JD Edwards v7.3)", "description": "", "end_date": "January 2001", "start_date": "September 1999"}, {"company": "Client: Valdese Weavers", "title": "EDI Project Lead; Programmer Analyst (SAP EDI)", "description": "", "end_date": "July 1999", "start_date": "January 1999"}, {"company": "Client: Century Furniture, Hickory, NC", "title": "EDI Project Lead; Programmer Analyst (SAP EDI)", "description": "", "end_date": "July 1999", "start_date": "March 1997"}], "Name": {"middle": "", "last": "Santon", "First": "Germaine"}, "summary": "', '    EXPERIENCE:', '', 'AS400 / i-Series:  RPG / COBOL:  EDI:  JD Edwards (Oracle) ', 'Implementations / Conversions / Integration / Design / Programming / Testing / Documentation / User Training', '', 'EDI translators / AS2: ', 'NuBridges Trailblazer, now Liaison Technologies', 'Sterling Gentran  ', 'Inovis (a.k.a. Premenos, Harbinger Trusted Link, Peregrine)', 'SAP IDOC (EDI mapping ONLY with both Gentran and Inovis)', 'EXTOL: certified 2003 ', '', 'EDUCATION: ', 'UNC-Charlotte:  Bachelor of Science, Computer Science', 'Youngstown State Univ:  Associate in Applied Science, Computer Technology  ', 'UNC-Charlotte:  Project Management Curriculum  2010', 'UNC-Charlotte:  Business Analysis Certification course work  2009 ', 'EDI exposure to PKMS WMS  2010', 'Exposure to C#, Visual Studio (dot.net)  2009', '", "Connections": "62", "specialties": "\\,r,\\,n,O,r,a,c,l,e,O,W,v,7,.,3,(,O,M,W,/,v,e,r,s,i,o,n,s,/,n,a,v,i,g,a,t,i,o,n,),\\,r,\\,n,\\,r,\\,n,R,P,G,\\,r,\\,n,\\,r,\\,n,E,D,I,\\,r,\\,n,\\,r,\\,n,J,D,E,d,w,a,r,d,s,\\,r,\\,n,\\,r,\\,n,I,n,t,e,g,r,a,t,i,o,n,\\,r,\\,n,\\,r,\\,n,P,r,o,g,r,a,m,m,i,n,g,\\,r,\\,n,\\,r,\\,n,C,O,B,O,L,\\,r,\\,n,\\,r,\\,n,I,B,M,i,S,e,r,i,e,s,\\,r,\\,n,\\,r,\\,n,E,R,P,\\,r,\\,n,\\,r,\\,n,O,r,a,c,l,e,\\,r,\\,n,\\,r,\\,n,S,y,s,t,e,m,s,A,n,a,l,y,s,i,s,\\,r,\\,n,\\,r,\\,n,I,T,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-Btk4lZSdpsRp6mGKkhxVTRwIXxCJL2HxXWxxWNUgX1L6M0hHBtkxWpkdXix5K8_ITKSj/germaine-santon.jpg", "Location": {"country": "US", "state": "NC", "city": "Charlotte"}, "Recommendations": "7", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVIOet2Lv3OFcTxSkChs9ZMer2U06fKT7iqOEM3Ssc61N&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_b68f22d2771910d9.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "afhdfgfgd", "First": "dasdasd"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "NY", "city": "Albany"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVwuONBMUdY03iqaC4YdA3mgBFtfZ6ig-H6gBxGwXWJH6&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_cc8a4a10f19c98f7.PROFILE.json
{"Jobs": [{"company": "Meddle Finance and Business", "title": "Gerente de Projetos", "description": "', 'Especifica\u00e7\u00e3o, planejamento, desenho, execu\u00e7\u00e3o e acompanhamento de projetos complexos em planejamento estrat\u00e9gico e financeiro, intelig\u00eancia de neg\u00f3cios (BI), gerencia de processos de neg\u00f3cios (BPM) e controle de produ\u00e7\u00e3o. Membro do Comit\u00ea T\u00e9cnico internacional da ISO, TC258/SG1, para Governan\u00e7a de Projetos. Membro do Comit\u00ea CEE93 da ABNT para a Norma ABNT-ISO21500 - Gest\u00e3o de Projetos.', '", "end_date": "", "start_date": "February 2011"}, {"company": "Entre em contato agora mesmo (21)8858-5492", "title": "Planejamento, Estrat\u00e9gia, T\u00e1tica e Resultados - Inteligencia de Neg\u00f3cios", "description": "', 'Business Strategy, Marketing, Business Intelligence, Information Technology', '", "end_date": "March 2011", "start_date": "September 2010"}, {"company": "CIPA - Participa\u00e7\u00f5es e Administra\u00e7\u00e3o SA", "title": "Gerente, Inteligencia de Neg\u00f3cios", "description": "', \"Board Executive Assessor, Strategy and Market Intelligence, responsible for specification, deployment and management of Business Intelligence model for the group's business units.\", \"Broadened the scope and functions of the company's CRM, allowing extraction of information, analysis and decision making on customer's behavioral profiles.\", 'Promoted the integration of corporate databases, providing capital information for strategic guidelines aimed at operational procedures adjustments, setting efficiency and effectiveness standards compatible to external customers needs, thus supporting their loyalty.', '", "end_date": "September 2010", "start_date": "September 2006"}, {"company": "CONTRASTE", "title": "Marketing and Alliances, Manager", "description": "', '* Marketing and Alliances, Manager, reporting directly to the Executive Director and owner.', '* Committed to design and deploy the Marketing and Alliances area. ', '* Established partnership agreements with main technology providers - like IBM, BEA, Tibco - as systems integrator for Brazil and Latin America, leading certification processes, sales and technical team training, and new products development.', '* Designed, deployed and coordinated the market communication process, so that Contraste became a recognized and respected brand in the national and Latin American systems integration sector, resulting in 100% sales increase in 2004 and equivalent pipeline for 2005, as well as 26 press releases published by the specialized media within one year.', '* Established the entry point into the international market through the participation in the negotiation of one project consortium in the USA and two in Mexico which demanded fluency in English and Spanish.', '", "end_date": "January 2005", "start_date": "January 2004"}, {"company": "Extend Software", "title": "Marketing, Director", "description": "', '* Marketing Director, committed to creation, development and implementation of strategic planning, branding, press relationship and product re-engineering for worldwide market, conquering 32% real revenue increase in 2002 and 35% in 2003.', '* Lead Generation: Development and deployment, reaching 50 leads/month.', '* Press Relationship, resulting in 12 releases per month along the last two years, overcoming the competence rates in more than 30%.', '* International Trade Relationship: OEM agreement with relevant international IT providers, reaching 20% total revenue from software exportation to USA, Canada, Europe and Asia. ', '* Mentor of agreements with government financial entities aiming the offer of financing for Business Analytics solutions to the customers. ', '* Planning and coordination of institutional (focused on invigoration of the institutional image and branding) and commercial events (focused on lead generation). ', '* Host for international partners in visit to Brazil.', '", "end_date": "January 2004", "start_date": "January 2002"}, {"company": "Clarent Corporation", "title": "Director, Sales Engineering", "description": "', \"* Area Director, Sales Engineering, Latin America, committed to increase market share of Clarent's IP Telephony solutions throughout Latin America countries. Reporting to Area Vice President, Sales. In charge of RFP/RFI responding and prospects.\", '* Performance in Sales Summits with suppliers and international partners, as exhibitor and defender of the commercial interests of the Latin-American area.', '", "end_date": "September 2001", "start_date": "September 1999"}, {"company": "Embratel", "title": "Assessor de TI - Dir. Comercial", "description": "', '* Strategic planning, process, quality and IT management for Large Accounts Sales Directory, supporting sales, customer service and technical consulting processes.', '* I mapped and optimized technical consulting processes for Rio de Janeiro Sales Office, resulting in 66% in Complex Bid Modeling Average Time (from 60 days to 20 days).', \"* I joined the Supervisor Team for the outsourced implementation of the Optical Cable Unisur's Administration system.\", '* I managed the integration of the International Transmission Management Centers in Rio de Janeiro and S\u00e3o Paulo, via a LAN-based computer system that reduced to 30% the time spent in circuitry recovery.', '* I reduced from 14 days up to 8 minutes, with zero error performance, the time spent to process and transfer International Circuitry Monthly Faults data to the International Billing processes.', '* I increased in 7 years (March, 1997) the Metaconta International Switch life cycle, which resulted in plus 35% in its total life cycle.', '", "end_date": "September 1999", "start_date": "October 1983"}], "Name": {"middle": "", "last": "Lelles", "First": "Robson"}, "summary": "', '* Executive, Strategy and Market Intelligence, responsible for specification, deployment and management of Business Intelligence and BPM models.', '* ISO TC258/SG1 Comittee Member, on Project Governance.', '* ABNT CEE93 Comittee Member, working on ABNT ISO 21.500 standard - Project Management.', \"* Broadened the scope and functions of the company's CRM, allowing extraction of information, analysis and decision making on customer's behavioral profiles.\", '* Promoted integration of corporate databases, providing information for strategic guidelines, standards compliance and customers needs.', '* Marketing Executive, committed to creation, development and implementation of strategic planning, branding, press relationship and product re-engineering for worldwide market, reaching real revenue increase.', '* Lead Generation: Development and deployment, through seminars, workshops and trade shows. ', '* Press Relationship: Establishment and strengthening, overcoming the competence rates over 30%. ', '* International Trade Relationship: OEM agreement with relevant Business Analytics Technology international providers, reaching 20% total revenue from USA, Canada, Europe, Asia. ', '* National Trade Relationship: Partnership agreements with complimentary segments companies - telecommunication, data mining - in order to widen business opportunity through the offer of bundle solutions.', '* Sales Engineering Director, Latin America, committed to projects and commercial proposals for telecommunication services providers and corporate market in Latin America, deploying regional sales offices in Argentina, Brazil, Colombia and Mexico.', '* 25+ years experience in project co-ordination in Telecommunications and Information Technology.', \"* IT, PMO and QM Support for Embratel's Large Accounts Regional Sales Directory in Rio de Janeiro.\", \"* Technical Consulting for Embratel's Sales Office in Rio de Janeiro.\", \"* Losango Award '92 Winner, with the work \"Multimedia Shopping: Transition Mechanism for the Bookstore's Market\".\", '", "Connections": "500+", "specialties": "\\,r,\\,n,B,P,M,N,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,I,n,t,e,l,l,i,g,e,n,c,e,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,S,t,r,a,t,e,g,y,\\,r,\\,n,\\,r,\\,n,G,u,i,t,a,r,P,l,a,y,e,r,\\,r,\\,n,\\,r,\\,n,B,u,s,i,n,e,s,s,M,a,n,a,g,e,m,e,n,t,\\,r,\\,n,\\,r,\\,n,T,e,a,m,L,e,a,d,e,r,s,h,i,p,\\,r,\\,n,\\,r,\\,n,T,e,l,e,c,o,m,m,u,n,i,c,a,t,i,o,n,s,\\,r,\\,n,\\,r,\\,n,P,M,O,\\,r,\\,n,\\,r,\\,n,C,u,s,t,o,m,e,r,R,e,l,a,t,i,o,n,s,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-De9dqIqb1i7TAuhWw6pFwDbY6I5zz3OqaDiDS7Bq6GXGzTGdDe9DYs5b6sgzchpNKiMC/robson-lelles.jpg", "Location": {"country": "BR", "state": "RJ", "city": ""}, "Recommendations": "25", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVBakmvVHN9g5eJWBzXHhiAI2W5KmfWMoC7SKrW3xeV04&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_a9d86189ea4e4d10.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Ds", "First": "Johnson"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "VA", "city": "Roanoke"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVBEhyI87Loxg68EiCjx-kQK4YBLdEaSpnuygb7mU978r&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_fefa1799869b3653.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Lynch", "First": "Carol"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "VA", "city": "Norfolk"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVz_u2H9DIM7eQRgNLpEteqrJe5uBSr4tBQ9cZE4ZAiwr&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_018d5fa8f87be3c1.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Bert", "First": "Quick"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "MA", "city": "Marshfield"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVLdN7XkvMXjEjjwQTIorj6isdIazxeNMBhvz6dDxG9bG&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_bd07b2dfde624289.PROFILE.json
{"Jobs": [{"company": "Schock Design", "title": "Owner", "description": "', 'Schock Design helps companies design and develop simple, easy, successful Web software at all points of the process, from concept to launch.', '", "end_date": "", "start_date": "January 1997"}, {"company": "Savings.com", "title": "User Interface Engineer", "description": "', 'Working with other stakeholders to create fast, compelling user experiences for highly-trafficked deals Web site. Specialist in client-side technologies, including HTML, CSS, YUI, jQuery, Backbone.js, Java, Velocity; resident Git expert; UX and paper prototyping; agile methodologies.', '', 'Helped lead an intense, month-long project to design and implement a new company-changing personalization product. Roles included product development, engineering, UX, and project management. Delivered what we promised, and on time.', '", "end_date": "August 2011", "start_date": "March 2010"}, {"company": "Applied Minds", "title": "User Interface Engineer", "description": "', 'Responsible for all user interface design and development for video sharing Web application. Led concept development and paper prototyping with team. Wrote clean XHTML, utilized frameworks like YUI and jQuery, and dazzled eyes with CSS. Using AJAX and JSON elements, and modern optimization techniques -- like compression, caching and minification -- created a speedy, responsive user experience.', '", "end_date": "November 2009", "start_date": "January 2009"}, {"company": "Layout Solutions, Inc", "title": "Web Development Director", "description": "', 'Overseeing and executing all aspects of Web application development for clients, from initial consulting to launch. XP-style requirements gathering, paper prototyping, user experience design, Rails development, server management, application deployment.', '", "end_date": "December 2008", "start_date": "January 2008"}, {"company": "Procore Technologies, Inc.", "title": "Contract Web Developer", "description": "', 'Provided design and development services for their core product.', '", "end_date": "February 2007", "start_date": "December 2006"}, {"company": "Below the Line Magazine", "title": "Online Manager", "description": "', \"- Designed/developed the magazine's Web presence\", '- Designed/developed several robust Web applications to supplement their print publication, supporting several thousand users.', '- Managed & configured Web servers and technology', '", "end_date": "November 2006", "start_date": "July 2001"}, {"company": "Jason Schock Photography", "title": "Owner", "description": "', 'Specializing in editorial and sports.', '", "end_date": "2006", "start_date": "August 1998"}, {"company": "Fastclick", "title": "Software Engineer/ UI Designer", "description": "', '- Initiated, designed, & developed an application (called CHIMP) to improve internal communication & workflow', '- Designed the user interface for a skunk-works search advertising software project', '", "end_date": "September 2005", "start_date": "May 2004"}, {"company": "Benefit Software, Inc.", "title": "Web Developer", "description": "', 'Developed Web-based employee benefits software.', '", "end_date": "October 2003", "start_date": "June 2003"}, {"company": "Fionda, LLC", "title": "Contract Web Developer", "description": "', 'Worked on database-intensive Web application for managing over a million telecommunications customer records and related metrics.', '", "end_date": "June 2003", "start_date": "May 2003"}, {"company": "University of California, Santa Barbara", "title": "Web Designer/Developer", "description": "', 'Initiated, oversaw, designed and developed the redesign of the Admissions and Outreach Web site, improving information accessibility. Designed and developed custom Web applications for staff and public', '", "end_date": "August 2002", "start_date": "June 2001"}, {"company": "UCSB Daily Nexus", "title": "Online Editor", "description": "', 'Initiated, designed, and developed a database-driven, community-based Web site for the student daily newspaper. Responsible for all online content. Trained junior Web team members.', '", "end_date": "June 2001", "start_date": "August 2000"}, {"company": "UCSB Daily Nexus", "title": "Photo Editor", "description": "', 'Responsible for all daily photo content at student paper: editing, giving out assignments to junior photographers, production. Also handled numerous daily photo assignments, as well as departmental purchasing and payroll.', '", "end_date": "December 2000", "start_date": "November 1998"}, {"company": "North County Times", "title": "ISP Support Technician", "description": "', \"Provided phone support to customers of the newspaper's dial-up Internet service.\", '", "end_date": "August 1998", "start_date": "January 1998"}], "Name": {"middle": "", "last": "Schock", "First": "Jason"}, "summary": "', 'Broadly experienced Web ninja who produces creative, polished, professional Web-based products with high attention to detail. Hands-on knowledge of everything it takes to get a Web project online, from design to deployment. Deep understanding of how to design products that customers find easy to use.', '', \"I've worked for a variety of companies over the years; startup atmosphere is preferred.\", '", "Connections": "168", "specialties": "\\,r,\\,n,U,s,e,r,E,x,p,e,r,i,e,n,c,e,\\,r,\\,n,\\,r,\\,n,I,n,t,e,r,a,c,t,i,o,n,D,e,s,i,g,n,\\,r,\\,n,\\,r,\\,n,U,s,a,b,i,l,i,t,y,\\,r,\\,n,\\,r,\\,n,U,s,e,r,I,n,t,e,r,f,a,c,e,D,e,s,i,g,n,\\,r,\\,n,\\,r,\\,n,U,s,e,r,I,n,t,e,r,f,a,c,e,\\,r,\\,n,\\,r,\\,n,I,n,f,o,r,m,a,t,i,o,n,A,r,c,h,i,t,e,c,t,u,r,e,\\,r,\\,n,\\,r,\\,n,j,Q,u,e,r,y,\\,r,\\,n,\\,r,\\,n,H,T,M,L,\\,r,\\,n,\\,r,\\,n,C,S,S,\\,r,\\,n,\\,r,\\,n,R,u,b,y,o,n,R,a,i,l,s,\\,r,\\,n,\\,r,\\,n,S,E,O,\\,r,\\,n,\\,r,\\,n,S,E,M,\\,r,\\,n,\\,r,\\,n,U,s,e,r,E,x,p,e,r,i,e,n,c,e,\\,r,\\,n,\\,r,\\,n,O,n,l,i,n,e,A,d,v,e,r,t,i,s,i,n,g,\\,r,\\,n,\\,r,\\,n,W,e,b,A,n,a,l,y,t,i,c,s,\\,r,\\,n", "image_url": "http://m3.licdn.com/mpr/pub/image-VFPvOu7vUvn8tSN8iQVKjOsVW3jTniKmoFHHxuhXWqRaU1zqVFPHifOvWblQUKjkJ9lf/jason-schock.jpg", "Location": {"country": "US", "state": "CA", "city": "Irvine"}, "Recommendations": "2", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVFtZIVm9KAyXzk6wUF2QMcA92hLp9D_qOeK2qB0dkpKh&trk=pprof-0-ts-view_full-0"}
