=== razrog/pipl_test/linkedin_schema.json
{"$schema": "http://json-schema.org/draft-04/schema#","type": "object","properties":{"Jobs":{"type": "array","properties":{"company": {"type": "string"},"description": {"type": "string"},"start_date": {"type": "string"},"end_date": {"type": "string"},"title": {"type": "string"}}},"Name": {"type": "object","properties":{"middle": {"type": "string"},"last": {"type": "string"},"First": {"type": "string"}}},"summary":{"type": "string"},"Connections": {"type": "string"},"specialties": {"type": "string"},"image_url": {"type": "string"},"Location": {"type": "object","properties":{"country": {"type": "string"},"state": {"type": "string"},"city": {"type": "string"}}},"Recommendations": {"type": "string"},"profile_url": {"type": "string"}}}

=== razrog/pipl_test/out/55_4658d18bf5940890.PROFILE.json
{"Jobs": [{"company": "The Meisel Group", "title": "Managing Partner", "description": "', '    The Meisel Group is a Boutique Solution Firm.', ' ', 'Propelling Your Business is Our Goal:', '', \"There comes a time when you realize that what you have been doing for months or maybe years...just isn't getting you the results that you believe you deserve.   This is when you contact The Meisel Group.\", '', 'The Meisel Group is focused on helping your business become the successful firm that it should be.', '', 'Every business wants to believe that there is a ', '\"Silver Bullet\" to increasing revenue and or changing the course of where their business is today.  ', '', \"But we all know the truth....there just isn't one! \", '', 'The Meisel Group works with your firm to create a plan that can be executed and become the next best thing to the \"Mythical\" Silver Bullet.', '', '', 'Contact us at: Contact@MeiselGroup.com ', '', 'Please also visit us on the web: ', 'www.MeiselGroup.com', '", "end_date": "", "start_date": "October 2011"}, {"company": "Gurnet Consulting", "title": "Vice President of Solution Development", "description": "', '    Gurnet is a Boutique Consulting firm which specializes in Program and Project Management solutions.  With practices and expertise in Data Management, Information Security, Data Center Solutions, and Application Development Gurnet is the firm to rely on for your most important Project.  ', '', 'Our clients include: TJX, Liberty Mutual, RMR, Staples, Starwood Hotels, RBS Citizens, Geiger Group, Houghton Mifflin, Circor, Au Bon Pain, the State of Rhode Island, Focus Brands and Dunkin Brands.', '', 'Our Consultants average more than 15 years of work experience and typically have worked within the big 4 consulting companies.  Our firm\u2019s executive team comes to Gurnet from HP, Microsoft, IBM, KPMG, CIBER, and MIT.   ', '', 'As Vice President of Solution Development David\u2019s job is to educate our existing and potential client base as to the value that only Gurnet can bring to their firm.', '", "end_date": "October 2011", "start_date": "January 2011"}, {"company": "Catalyst Solutions", "title": "Vice President of Solutions", "description": "', \"    David Meisel is Catalyst Solutions Vice President of Solutions.  David's role is to help this successful Information Technology Staffing Firm focused on the Healthcare vertical to expand within its current client base and to aggressively gain new clients while leading Catalyst to become a Boutique Solutions firm.  \", '', 'Through the hiring of Senior Solution Executives, combined with a focus on Principle and Senior Consultants for our clients in 2010 Catalyst was able to have record earnings.  ', '', 'Working with such premier accounts which include:', 'Trizetto, BCBS North Carolina, Cerner, Epic, Dell Healthcare, Meditech, Ab Initio, Blue Shield of California, AvMed, Broward Health, Premera, Regence, Mayo, Scripps, National Jewish, VCU Health, Amerigroup, Carefirst, BCBS Rhode Island, HCSC, BCBS Association, CIGNA, Aetna, Oracle, and IBM.', '', 'Capitalizing on the core of our success \u201cHuman Capital\u201d for the Payer, Providers, and Healthcare Vendors,   Catalyst  Solutions is becoming a leader in the Healthcare space.   By approaching each client with a solutions based approach we are able to understand our clients\u2019 needs to be successful today and through the life of their most pressing project.  ', '', 'Leveraging consulting principals of Access, Define and Implement Catalyst Solutions is not just a vendor to its clients but a true \u201cBusiness Partner\u201d.   ', '', 'Catalyst Solutions presently has offices in Denver, Los Angeles, Boston, and Puerto Rico with clients throughout the United States. ', '', '2011-New Name(From Catalyst Search to Catalyst Solutions), New Branding, New Website-www.catalystsolutions.com', '", "end_date": "January 2011", "start_date": "April 2010"}, {"company": "CIBER", "title": "Senior Business Development Executive", "description": "', '    As the Senior Business Development Executive at CIBER I was responsible for the majority of our Rhode Island, Connecticut, and Southern Massachusetts commercial clients.  Responsibilities included: Attracting new clients, managing of present accounts, expanding offerings within accounts,  overseeing solution delivery, client and consultant care, build and strengthen partner relationships, as well as business and technical consultant to CIBER and its clients. Solution focus included-Information Security(Application and Network Vulnerability, Secure Operation Center, Enterprise Vulnerability), Managed Information Technology Offerings(SOC, NOC), BI/DW and  Software Development.', '', 'Clients included:', 'CVS Caremark, RBS Citizens Bank, RBS WorldPay, Amica Insurance, BCBSRI, Dunkin Brands, EMC/RSA, Hasbro, Fidelity Investments, Staples, and TJX.', '", "end_date": "April 2010", "start_date": "May 2007"}, {"company": "Tango Pix, LLC", "title": "Vice President of Business Development", "description": "', '    Tango Pix was founded to provide local, regional, and national Digital Media Production.  As one of the founders of this firm my focus was on the aquistion of our clients.  Our clients include: Hasbro, NBC, CBS, ABC, BCBSRI, AMICA Insurance, APC, EMC, Fidelity Investments, Textron, FM Global, Rhode Island Hospital, Lifespan Hospital Group, State of Rhode Island, BIFF, RI Office of Economic Development, GBH, Wyndham Hotels, Brown University, Rhode Island School of Design, Roger Williams University, Southcoast Hospital, Showtime, and Neighborhood Health.', '", "end_date": "June 2007", "start_date": "July 2005"}, {"company": "Institute of Information Technology, Inc.", "title": "National Sales Manager", "description": "', '    National Sales Manager for this boutique GIS Product and Solution Services Firm.   Recruited and Managed National Sales Staff.   Clients include-Waste Management, City of Hartford, State of Connecticut, City of Woburn, CR&R, Dynamex, City of Houston, City of Newton-MA., City of Woburn-MA, and Shell Oil Company.', '", "end_date": "July 2005", "start_date": "November 2003"}, {"company": "Oracle", "title": "Regional Sales Manager", "description": "', '    Regional Sales Manager-Concentration was on Content Management.  Clients include-BMG, SONY, EMI Records, Warner Records, Time Inc, Pergo, Smithsonian, Hasbro Toy Company, BCBSRI, Cendent, Pearson Media, Neighborhood Health, Fidelity Investments, FM Global, and Amica Insurance.', '", "end_date": "June 2003", "start_date": "July 2001"}, {"company": "RealNetworks", "title": "Senior Recruiter", "description": "", "end_date": "June 2001", "start_date": "April 2000"}, {"company": "Microsoft", "title": "Senior Recruiter", "description": "", "end_date": "April 2000", "start_date": "February 1997"}, {"company": "Art Institute of Seattle", "title": "Senior Advisor", "description": "", "end_date": "February 1997", "start_date": "June 1994"}], "Name": {"middle": "", "last": "Meisel", "First": "David"}, "summary": "", "Connections": "500+", "specialties": "", "image_url": "http://m3.licdn.com/mpr/pub/image-eqoWP4zqYdUN5oYmxWXDxBcFIPpSxoKbehoFoh8qI4v7iA8geqoFiTRqI_zceIEEWRcI/david-meisel.jpg", "Location": {"country": "US", "state": "CA", "city": "Culver City"}, "Recommendations": "1", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVJgEJdtdSzLIZZdwt1S4QMnZBiKNXFM5-_xfdNUr5ynJ&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_53239249a64eb3c8.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Mukuddem", "First": "Mukhtar"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "ZA", "state": "GP", "city": "Johannesburg"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVKfc0K81v-OOraoO47iCXB2kwI1nPbtsTxaxXzOc3BKm&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_996bd83d815dc699.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Kaas", "First": "Kristina"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "SE", "state": "Stockholm County", "city": "Stockholm"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVB7OZYEmp36CoL2vHSpOzk0PjDypYHoBIETNmtA9h1Cp&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_c1001b6af8b1928c.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Kittles", "First": "Oshanda"}, "summary": "", "Connections": "2", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "GA", "city": "Atlanta"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVDTY9fXzs1WDuJL1smb9PRQGzNuIYMH4XhjHgwxGZnGo&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_fc87f180a48d6196.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Bennett", "First": "Tim"}, "summary": "", "Connections": "1", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "GA", "city": "Atlanta"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVFzdc9iWI7E3UXzK_c18tJIyaQJ6vo6fwpwKvsHyBszn&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_f4062223b81abba8.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Kingsbury", "First": "Karen"}, "summary": "", "Connections": "45", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "MA", "city": ""}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVDIMdAVGpVvjte2IEy7NmEW9ZxnWXTOR2pm74XZ0IWGi&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_0f215b20fac8bdaa.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "Williamson", "First": "Gordy"}, "summary": "", "Connections": "2", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "WI", "city": "Oshkosh"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVz97Y6p0lX618ehFKDhzXFXdQHRElYMdD62kSdjloivB&trk=pprof-0-ts-view_full-0"}

=== razrog/pipl_test/out/55_2f54c3abd4e4dc2c.PROFILE.json
{"Jobs": [], "Name": {"middle": "", "last": "reddy", "First": "aabu"}, "summary": "", "Connections": "0", "specialties": "", "image_url": "", "Location": {"country": "US", "state": "IL", "city": "McHenry"}, "Recommendations": "", "profile_url": "https://www.linkedin.com/reg/join-pprofile?_ed=0_dHB8G4tKSI1eNkyEd3uBk2dzQE2AkVU1r9kHbXjxPZGWJlD5Jt4ZMf87SacJnJbVJIwOV3aQMxBAnwLkJB-VVmG5LrreWjpElgL2AGjapvN&trk=pprof-0-ts-view_full-0"}
